{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "app.secretStoreName" $ }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecretName | default (printf "%s-secrets" (include "app.fullname" .)) }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}
