{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "stats-backend.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "stats-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ include "stats-backend.fullname" . }}-secrets
    creationPolicy: Owner
  data:
  - secretKey: ws-secret
    remoteRef:
      key: {{ .Values.externalSecrets.parameterPaths.wsSecret }}
{{- end }}
