apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- if .Values.externalSecrets.envSuffix }}
    environment: {{ .Values.externalSecrets.envSuffix }}
    {{- end }}
