# Production environment values for stats-backend

replicaCount: 3

namespace: stats-backend-prod

image:
  repository: 654654249872.dkr.ecr.us-east-2.amazonaws.com/stats-backend
  tag: latest

env:
  nodeEnv: production

ingress:
  enabled: true
  className: alb
  groupName: ""
  groupOrder: 100
  certificateArn: ""  # Add production ACM certificate ARN
  hosts:
    - host: stats-backend.testnet.rootstock.io
      paths:
        - path: /
          pathType: Prefix
  annotations: {}

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

externalSecrets:
  enabled: true
  parameterPaths:
    wsSecret: /stats-backend/prod/ws-secret
