# Development environment values for stats-backend

namespace: stats-backend-testnet

image:
  tag: testnet

env:
  nodeEnv: production

# Connect to external ALB via TargetGroupBinding
targetGroupBinding:
  enabled: true
  targetGroupArn: "arn:aws:elasticloadbalancing:us-east-2:654654249872:targetgroup/stats-service-cluster-api/aed5c0f224d895ba"
  targetType: instance

externalSecrets:
  enabled: true
  envSuffix: prod
  secrets:
    - secretKey: backend-password
      remoteKey: backend-password
